// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://athsmgatmkfiefivtyji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aHNtZ2F0bWtmaWVmaXZ0eWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDE0MDAsImV4cCI6MjA1NDE3NzQwMH0.B14_1-hvZMcMloyrPmlN9U-ugc5xfQW15WM8175mwl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);